# Generated by Django 3.0 on 2020-11-06 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roster',
            name='position',
            field=models.CharField(default='left bench', max_length=255),
            preserve_default=False,
        ),
    ]
